/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OpenAccountRouteImport } from './routes/open-account'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenAccountRoute = OpenAccountRouteImport.update({
  id: '/open-account',
  path: '/open-account',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/open-account': typeof OpenAccountRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/open-account': typeof OpenAccountRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/open-account': typeof OpenAccountRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/investing'
    | '/login'
    | '/markets'
    | '/open-account'
    | '/pricing'
    | '/sitemap.xml'
    | '/trading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/investing'
    | '/login'
    | '/markets'
    | '/open-account'
    | '/pricing'
    | '/sitemap.xml'
    | '/trading'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/investing'
    | '/login'
    | '/markets'
    | '/open-account'
    | '/pricing'
    | '/sitemap.xml'
    | '/trading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InvestingRoute: typeof InvestingRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  OpenAccountRoute: typeof OpenAccountRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradingRoute: typeof TradingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-account': {
      id: '/open-account'
      path: '/open-account'
      fullPath: '/open-account'
      preLoaderRoute: typeof OpenAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InvestingRoute: InvestingRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  OpenAccountRoute: OpenAccountRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradingRoute: TradingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
