/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OpenAccountRouteImport } from './routes/open-account'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenAccountRoute = OpenAccountRouteImport.update({
  id: '/open-account',
  path: '/open-account',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/open-account': typeof OpenAccountRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/open-account': typeof OpenAccountRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/open-account': typeof OpenAccountRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/investing'
    | '/login'
    | '/markets'
    | '/open-account'
    | '/pricing'
    | '/sitemap.xml'
    | '/trading'
    | '/verify-otp'
    | '/api/public/stripe-webhook'
    | '/api/public/track'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/investing'
    | '/login'
    | '/markets'
    | '/open-account'
    | '/pricing'
    | '/sitemap.xml'
    | '/trading'
    | '/verify-otp'
    | '/api/public/stripe-webhook'
    | '/api/public/track'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/investing'
    | '/login'
    | '/markets'
    | '/open-account'
    | '/pricing'
    | '/sitemap.xml'
    | '/trading'
    | '/verify-otp'
    | '/api/public/stripe-webhook'
    | '/api/public/track'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InvestingRoute: typeof InvestingRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  OpenAccountRoute: typeof OpenAccountRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradingRoute: typeof TradingRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-account': {
      id: '/open-account'
      path: '/open-account'
      fullPath: '/open-account'
      preLoaderRoute: typeof OpenAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InvestingRoute: InvestingRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  OpenAccountRoute: OpenAccountRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradingRoute: TradingRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
